=== SykkoAtHome/Bootcamp_Tester/kodilla-scratch/src/main/java/car.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="car">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="manufacturer" type="xs:string"/>
                <xs:element name="model" type="xs:string"/>
                <xs:element name="year" type="xs:integer"/>
                <xs:element name="color" type="xs:string"/>
                <xs:element name="engine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="capacity" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="transmission" type="xs:string"/>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SykkoAtHome/Bootcamp_Tester/kodilla-scratch/src/main/java/car.xml
<?xml version="1.0" encoding="UTF-8"?>
<car xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="car.xsd">
    <manufacturer>Mazda</manufacturer>
    <model>6</model>
    <year>2022</year>
    <color>Deep Blue</color>
    <engine>
        <type>Gasoline</type>
        <capacity>2.5</capacity>
    </engine>
    <transmission>AT</transmission>
    <options>
        <option>AC</option>
        <option>Power Windows</option>
        <option>Bluetooth</option>
        <option>Leather Seats</option>
        <option>Bi-Xenon</option>
    </options>
</car>
